storage: /tmp/verdaccio
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
packages:
  "**":
    access: $anonymous
    publish: $anonymous
    proxy: npmjs
logs:
  - { type: stdout, format: pretty, level: warn }
